### ISSUE TITLE
Reg : Ardupilot

### ISSUE THREAD

**Issue by johnd2010** [ctu-mrs/mrs_uav_hw_api#1]
Hi,
Thank you for sharing your research.
I was wondering if it would be possible to support ardupilot. 
Would it suffice to launch ardupilot separately from the mrs workspace? Will mrs_uav_hw_api still function as expected.

Thanks and Regards,
John D

**Comment by klaxalk** [comment]
Hey, it is possible to support Ardupilot, however, we don't have the capacity now for development and testing of the HW API. I am vaguely familiar with the fact the you can also use Mavros to communicate with Ardupilot. However, I don't know if the topics both in and out are the same as with PX4 and if the functionality will be compatible. You can try running the `mrs_uav_px4_api` (https://github.com/ctu-mrs/mrs_uav_px4_api) and you will see... If there are differences, then I suggest creating a copy of that and modifying it according to your needs.

**Comment by johnd2010** [comment]
Thank you for the prompt response.
